In [2]:
import pandas as pd
import json

In [30]:
with open('D:/056.의약품, 화장품 패키징 OCR 데이터/01.데이터/1. Training/라벨링데이터/TL1/result\medicine/annotations/medicine_00001.json') as f :
    js = json.loads(f.read())

In [31]:
df = pd.DataFrame(js)

In [38]:
images = df["images"][0]
image_df = pd.DataFrame(images.values())
image_df.index = images.keys()
image_df

                                           0
identifier                    medicine_00001
name                      medicine_00001.jpg
type                                     jpg
width                                   2694
height                                  2078
data_captured            2021:09:19 14:02:34
shutter_speed                            320
f_stop                                   1.8
gps
age                                       53
gender                                female
writer_num             psjspaspa96@naver.com
shooting_env                              실내
dust                                      없음
class                                    의약품
product_name      레복사신점안액0.5%(레보플록사신수화물) 5ml
product_category                   의약품_전문의약품

In [37]:
annotations = df["annotations"][0]
annotations_df = pd.DataFrame(annotations.values())
annotations_df.index = annotations.keys()
annotations_df

,0,1,2,3,4,5,6,7,8,9
polygons,"{'id': '005cc8c0-ca7e-44b2-8719-66f5a1878c9a',...","{'id': '7290b057-676c-462b-bfa1-409b0aae2211',...","{'id': 'eb6bbc8a-57da-436f-a526-0fe3655addee',...","{'id': 'b8cc944b-e761-4dbd-a960-d133fa5ca5f0',...","{'id': '9fe2943b-1a93-468d-9360-67bd2d59da67',...","{'id': 'c5ae1c0f-c3bd-4615-9bf1-ef114b25c52c',...","{'id': '9cac2b9e-5d2e-4a57-8192-f80ed50b5109',...","{'id': '94403693-48ca-4b7e-86a9-a83dc6e8e688',...","{'id': '68bd1564-a7e7-4d63-a66f-a93ee3374391',...","{'id': 'bbf90605-3b85-454f-b100-7c353a5c3e4c',..."
bbox,"{'id': '005cc8c0-ca7e-44b2-8719-66f5a1878c9a',...","{'id': '7290b057-676c-462b-bfa1-409b0aae2211',...","{'id': 'eb6bbc8a-57da-436f-a526-0fe3655addee',...","{'id': 'b8cc944b-e761-4dbd-a960-d133fa5ca5f0',...","{'id': '9fe2943b-1a93-468d-9360-67bd2d59da67',...","{'id': 'c5ae1c0f-c3bd-4615-9bf1-ef114b25c52c',...","{'id': '9cac2b9e-5d2e-4a57-8192-f80ed50b5109',...","{'id': '94403693-48ca-4b7e-86a9-a83dc6e8e688',...","{'id': '68bd1564-a7e7-4d63-a66f-a93ee3374391',...","{'id': 'bbf90605-3b85-454f-b100-7c353a5c3e4c',..."

In [40]:
annotations_df[0].bbox cv

{'id': '005cc8c0-ca7e-44b2-8719-66f5a1878c9a',
 'x': 618.8790117005273,
 'y': 223.058390996303,
 'width': 1728.205525300914,
 'height': 180.14412636688292}

                                           0
identifier                    medicine_00001
name                      medicine_00001.jpg
type                                     jpg
width                                   2694
height                                  2078
data_captured            2021:09:19 14:02:34
shutter_speed                            320
f_stop                                   1.8
gps
age                                       53
gender                                female
writer_num             psjspaspa96@naver.com
shooting_env                              실내
dust                                      없음
class                                    의약품
product_name      레복사신점안액0.5%(레보플록사신수화물) 5ml
product_category                   의약품_전문의약품